###############################################################################
# SET GENERAL PARAMETERS
###############################################################################
ATARI_ENV: PongDeterministic-v4
RENDER: True
STEPS: 250000
VERBOSE_STEPS: 1000
WARM_UP_STEPS: 50000
SUMMARY_PATH: logs

###############################################################################
# SET GENERATOR PARAMETERS
###############################################################################
GEN_DATA_PATH: data


###############################################################################
# SET OFFLINE TRAINING PARAMETERS
###############################################################################
TRAIN_DATA_PATH: data
EPOCHS: 10
BATCH_SIZE: 128
EVAL_EPISODES: 2
EVAL_RENDER: True


###############################################################################
# SET AUTOENCODER PARAMETERS
###############################################################################
AUTO_GENERATE: False
AUTO_SAVE_PATH: autoencoder
AUTO_EPOCHS: 100
AUTO_BATCH_SIZE: 128

