###############################################################################
# SET GENERAL PARAMETERS
###############################################################################
ATARI_ENV: PongDeterministic-v4
RENDER: False
STEPS: 500000
VERBOSE_STEPS: 1000
WARM_UP_STEPS: 50000
SUMMARY_PATH: logs

###############################################################################
# SET GENERATOR PARAMETERS
###############################################################################
GEN_DATA_PATH: data


###############################################################################
# SET OFFLINE TRAINING PARAMETERS
###############################################################################
TRAIN_DATA_PATH: data/DQN_500k
EPOCHS: 125
BATCH_SIZE: 128
EVAL_EPISODES: 10
EVAL_RENDER: False
