###############################################################################
# SET GENERAL PARAMETERS
###############################################################################
GYM_ENV: Breakout-v0
STEPS: 500
VERBOSE_STEPS: 100
DATA_PATH: data
SUMMARY_PATH: logs