###############################################################################
# SET GENERAL PARAMETERS
###############################################################################
STEPS: 500
VERBOSE_STEPS: 100
DATA_PATH: data
SUMMARY_PATH: logs

###############################################################################
# SET GYM PARAMETERS
###############################################################################
GYM_ENV: Breakout-v0
