###############################################################################
# SET GENERAL PARAMETERS
###############################################################################
EXECUTABLE: basic
STEPS: 1000000
VERBOSE_STEPS: 10
CHECKPOINTS: 50000
NO_GRAPHICS: False

###############################################################################
# SET GYM PARAMETERS
###############################################################################
GYM_ENV: LunarLander-v2