###############################################################################
# SET GENERAL PARAMETERS
###############################################################################
STEPS: 2000
VERBOSE_STEPS: 100
DATA_PATH: /media/Dataz/Space_Invaders

###############################################################################
# SET GYM PARAMETERS
###############################################################################
GYM_ENV: SpaceInvaders-v0
