###############################################################################
# SET GENERAL PARAMETERS
###############################################################################
EXECUTABLE: basic
STEPS: 1000
VERBOSE_STEPS: 10
CHECKPOINTS: 50000
NO_GRAPHICS: False