###############################################################################
# SET GENERAL PARAMETERS
###############################################################################
ATARI_ENV: PongDeterministic-v4
RENDER: False
STEPS: 1000000
VERBOSE_STEPS: 1000
WARM_UP_STEPS: 1
SUMMARY_PATH: logs

###############################################################################
# SET GENERATOR PARAMETERS
###############################################################################
GEN_DATA_PATH: data


###############################################################################
# SET OFFLINE TRAINING PARAMETERS
###############################################################################
AGENT: REM
TRAIN_DATA_PATH: data/DQN_1m
EPOCHS: 200
BATCH_SIZE: 256
EVAL_EPISODES: 10
EVAL_RENDER: False

LEARNING_RATE: 0.0005
GAMMA: 0.99
NUM_HEADS: 64
TARGET_UPDATE_INTERVAL: 2500
SUMMARY_CHECKPOINT: 1000


###############################################################################
# SET AUTOENCODER PARAMETERS
###############################################################################
AUTO_GENERATE: True
AUTO_SAVE_PATH: autoencoder
AUTO_EPOCHS: 250
AUTO_BATCH_SIZE: 128

